routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::prefix('admin')->group(function() {

		Route::get('/', 'Admin\DashboardController@index')->name('dashboard.index');

		Route::prefix('category')->group(function(){
			Route::name('category.')->group(function(){
				Route::post('/', 'Admin\CategoryController@store')->name('store');
				Route::get('/', 'Admin\CategoryController@index')->name('index');
				Route::get('/create', 'Admin\CategoryController@create')->name('create');
				Route::delete('/{model}', 'Admin\CategoryController@destroy')->name('destroy');
				Route::put('/{model}', 'Admin\CategoryController@update')->name('update');
				Route::get('/{model}', 'Admin\CategoryController@show')->name('show');
				Route::get('/{model}/edit', 'Admin\CategoryController@edit')->name('edit');
			});
		});
		
		Route::name('tag.')->group(function(){
			Route::post('tag', 'Admin\TagController@store')->name('store');
			Route::get('tag', 'Admin\TagController@index')->name('index');
			Route::get('tag/create', 'Admin\TagController@create')->name('create');
			Route::delete('tag/{model}', 'Admin\TagController@destroy')->name('destroy');
			Route::put('tag/{model}', 'Admin\TagController@update')->name('update');
			Route::get('tag/{model}', 'Admin\TagController@show')->name('show');
			Route::get('tag/{model}/edit', 'Admin\TagController@edit')->name('edit');
		});

		Route::name('product.')->group(function(){
			Route::post('product', 'Admin\ProductController@store')->name('store');
			Route::get('product', 'Admin\ProductController@index')->name('index');
			Route::get('product/create', 'Admin\ProductController@create')->name('create');
			Route::delete('product/{model}', 'Admin\ProductController@destroy')->name('destroy');
			Route::put('product/{model}', 'Admin\ProductController@update')->name('update');
			Route::get('product/{model}', 'Admin\ProductController@show')->name('show');
			Route::get('product/{model}/edit', 'Admin\ProductController@edit')->name('edit');
			
			Route::post('product/images', 'Admin\ProductController@imageStore')->name('image.store');
			Route::get('product/{model}/images', 'Admin\ProductController@images')->name('images');
			Route::delete('product/images/{image}', 'Admin\ProductController@imageDestroy')->name('image.destroy');
		});

		Route::get('configuration', 'Admin\ConfigurationController@edit')->name('configuration.edit');
		Route::put('configuration', 'Admin\ConfigurationController@update')->name('configuration.update');
	});

	

	Route::get('table/category', 'Admin\CategoryController@dataTable')->name('table.category');
	Route::get('table/tag', 'Admin\TagController@dataTable')->name('table.tag');
	Route::get('table/product', 'Admin\ProductController@dataTable')->name('table.product');

	Route::get('export/product', 'Admin\ProductController@export')->name('product.export');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('customer')->group(function() {
	Route::get('/login', 'Auth\CustomerLoginController@showLoginForm')->name('customer.login');
	Route::post('/login', 'Auth\CustomerLoginController@login')->name('customer.login.submit');
	Route::get('/', 'CustomerController@index')->name('customer.dashboard');
});

// Route::resource('admin/category', 'Admin\CategoryController');
Route::post('admin/users/search', 'Admin\UserController@search')->name('users.search');
Route::resource('admin/users', 'Admin\UserController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Product extends Model
{
   use Sluggable;

   /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','name','category_id','description','keywords', 'price','stock', 'slug','image', 'weight', 'size', 'status', 'code'
    ];

    /**
    * Return the sluggable configuration array for this model.
    *
    * @return array
    */
   public function sluggable()
   {
      return [
            'slug' => [
                'source' => 'name'
            ]
        ];
   }

  // public function getRouteKeyName()
  // {
  //     return 'slug';
  // }

  public function category()
  {
    return $this->hasOne('App\Category' , 'id', 'category_id');
  }

  public function tags()
  {
      return $this->belongsToMany('App\Tag', 'product_tag')
        ->withTimestamps();

  }

  public function images()
  {
    return $this->hasMany('App\Image');
  }

  public function getTagListAttribute()
  {
    return $this->tags->pluck('id');
  }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Exports\ProductsExport;
use App\Http\Requests\ProductRequest;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\FileUploadTrait;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\DataTables;
use File;


use App\Product;
use App\Category;
use App\Tag;
use App\Image;

class ProductController extends Controller
{
    use FileUploadTrait;
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.pages.products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Product();
        $categories = Category::pluck('name', 'id')->prepend('Pilih Kategori');
        $tags = Tag::pluck('name', 'id')->prepend('Pilih Kategori');
        $status = $this->status();
        return view('admin.pages.products.form', compact('model','categories', 'tags','status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {    
        $request = $this->saveFiles($request);
        $request['user_id'] = 1;
        $product = Product::create($request->all());
        $product->tags()->attach($request->input('tag_list'));

        return redirect(route('product.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $model)
    {
        return view('admin.pages.products.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $model)
    {
        $categories = Category::pluck('name', 'id');
        $tags = Tag::pluck('name', 'id')->prepend('Pilih Kategori');
        $status = $this->status();
        return view('admin.pages.products.form', compact('model','categories','tags', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $model)
    {
        if ($request->hasFile('image')){
            !empty($model->image) ? File::delete(public_path('uploads/product/' . $model->image)) : null;
            !empty($model->image) ? File::delete(public_path('uploads/thumb/' . $model->image)) : null;
            $request = $this->saveFiles($request);
        }
        
        $model->update($request->all());
        $model->tags()->sync($request->input('tag_list'));
        return view('admin.pages.products.index')->with(['success' => '<strong>' . $model->name . '</strong> Diperbaharui']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $model)
    {
        if(!empty($model->image)) {
            File::delete(public_path('uploads/product/' . $model->image));
            File::delete(public_path('uploads/thumb/' . $model->image));
        }

        $model->delete();
    }

    public function images (Product $model)
    {
        $images = Image::where('product_id', $model->id)->get();
        return view('admin.pages.products.images', compact('model', 'images'));
    }

    public function imageStore(Request $request)
    {
        $request = $this->saveFiles($request);
        Image::create($request->all());
        return back();
    }

    public function imageDestroy(Image $image)
    {
        if(!empty($image->image)) {
            File::delete(public_path('uploads/product/' . $image->image));
            File::delete(public_path('uploads/thumb/' . $image->image));
        }
        $image->delete();
        // return back();
    }


    public function dataTable()
    {
        $model = Product::with('category', 'tags')->withCount('images');

        return DataTables::of($model)
        ->addColumn('tag', function (Product $product) {
           
            $tagItem = '';
            foreach ($product->tags as $tag) {
                $tagItem .= '<span class="badge badge-warning">'.$tag->name.'</span> </br>';
            }
            return $tagItem;
        })
        ->addColumn('category', function (Product $product) {
            return $product->category->name; 
        })
        ->addColumn('action', function ($model) {
            return view('admin.layouts._action_nm', [
                'model' => $model,
                'image_count' => $model->images_count,
                'url_images' => route('product.images', $model->id),
                'url_show' => route('product.show', $model->id),
                'url_edit' => route('product.edit', $model->id),
                'url_destroy' => route('product.destroy', $model->id),
            ]);
        })
         ->addIndexColumn()
        ->rawColumns(['tag','action'])
        ->make('true');
    }

    public function export() 
    {
        return Excel::download(new ProductsExport, 'products.xlsx');
    }

    private function status()
    {
        return collect([
            ['step' => 'Publish', 'name' => 'Publikasikan'],
            ['step' => 'Draft', 'name' => 'Simpan sebagai Draft']
        ])
            ->pluck('name', 'step')->prepend('Pilih Status');
    }

}

resources/views/admin/pages/products/form.blade.php
@extends('admin.layouts.app')

@section('title', 'Produk')

@section('card-title', $model->exists ? 'Edit Produk' : 'Tambah Produk')

@section('content')
  
  {!! Form::model($model, [
      'route' => $model->exists ? ['product.update', $model->id] : 'product.store', 
      'method' => $model->exists ? 'PUT' : 'POST',
      'enctype' => 'multipart/form-data',
      'class' => 'form-horizontal'

  ])!!}

      {{-- {!! Form::open(array('route' => array('product.store'), 'method' => 'POST', 'enctype' => 'multipart/form-data', 'class' => 'form-horizontal')) !!} --}}

      <div class="form-group row">
        {!! Form::label('name', 'Nama Produk : ', array('class' => 'col-md-3 col-form-label-lg')) !!}
          <div class="col-md-8">
             {!!Form::text('name', null, ['class' => 'form-control form-control-lg'. ( $errors->has('name') ? ' is-invalid' : '' ), 'id' => 'name']) !!}
             {!! $errors->has('name') ? '<div class="invalid-feedback">'.$errors->first('name').'</div>':'' !!}
          </div>
      </div>

      <div class="form-group row">
        {!! Form::label('code', 'Kode Produk : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::text('code', null, ['class' => 'form-control'. ( $errors->has('code') ? ' is-invalid' : '' ), 'id' => 'code']) !!}
          {!! $errors->has('code') ? '<div class="invalid-feedback">'.$errors->first('code').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('category_id', 'Kategori : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!! Form::select('category_id', $categories, NULL, array('class' => 'form-control select2'. ( $errors->has('category_id') ? ' is-invalid' : '' )))!!}
          {!! $errors->has('category_id') ? '<div class="invalid-feedback">'.$errors->first('category_id').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('price', 'Harga : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::number('price', null, ['class' => 'form-control'. ( $errors->has('price') ? ' is-invalid' : '' ), 'id' => 'price', 'placeholder' => 'Tentukan Harga Produk']) !!}
          {!! $errors->has('price') ? '<div class="invalid-feedback">'.$errors->first('price').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('stock', 'Stok : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::number('stock', null, ['class' => 'form-control'. ( $errors->has('stock') ? ' is-invalid' : '' ), 'id' => 'stock', 'placeholder' => 'Tentukan Stok Produk']) !!}
          {!! $errors->has('stock') ? '<div class="invalid-feedback">'.$errors->first('stock').'</div>':'' !!}
        </div>
      </div>
      
      <div class="form-group row">
        {!! Form::label('weight', 'Berat : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::text('weight', null, ['class' => 'form-control'. ( $errors->has('weight') ? ' is-invalid' : '' ), 'id' => 'weight', 'placeholder' => 'Tentukan Berat Produk']) !!}
           {!! $errors->has('weight') ? '<div class="invalid-feedback">'.$errors->first('weight').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('size', 'Ukuran : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::text('size', null, ['class' => 'form-control'. ( $errors->has('size') ? ' is-invalid' : '' ), 'id' => 'size', 'placeholder' => 'Tentukan Ukuran Produk']) !!}
          {!! $errors->has('size') ? '<div class="invalid-feedback">'.$errors->first('size').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('description', 'Deskripsi : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::textarea('description', null, ['class' => 'form-control'. ( $errors->has('description') ? ' is-invalid' : '' ), 'id' => 'description']) !!}
          {!! $errors->has('description') ? '<div class="invalid-feedback">'.$errors->first('description').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('keywords', 'Keywords : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::textarea('keywords', null, ['class' => 'form-control'. ( $errors->has('keywords') ? ' is-invalid' : '' ), 'id' => 'keywords', 'rows' => 3]) !!}
           {!! $errors->has('keywords') ? '<div class="invalid-feedback">'.$errors->first('keywords').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('tags', 'Tag : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!! Form::select('tag_list[]', $tags, NULL, array('class' => 'form-control select2'. ( $errors->has('tags') ? ' is-invalid' : '' ),'multiple'))!!}
          {!! $errors->has('tags') ? '<div class="invalid-feedback">'.$errors->first('tags').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('image', 'Gambar : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::file('image', null, ['class' => 'form-control', 'id' => 'image']) !!}
          {!! Form::hidden('image_max_size', 5) !!}
          {!! Form::hidden('image_max_width', 2048) !!}
          {!! Form::hidden('image_max_height', 2048) !!}
          {!! $errors->has('image') ? '<div class="invalid-feedback">'.$errors->first('image').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('status', 'Status : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!! Form::select('status', $status, NULL, array('class' => 'form-control select2'. ( $errors->has('status') ? ' is-invalid' : '' )))!!}
          {!! $errors->has('status') ? '<div class="invalid-feedback">'.$errors->first('status').'</div>':'' !!}
        </div>
      </div>


      <div class="form-group row">
        {!! Form::label('button', '', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          
          {!! Form::button($model->exists ? 'Ubah':'Simpan', array('class' => 'btn btn-success btn-lg mr-2', 'type' => 'submit')); !!}
          {!! Form::button('Reset', array('class' => 'btn btn-warning btn-lg mr-2', 'type' => 'reset')); !!}
        </div>
      </div>



  {!! Form::close() !!}
      
@endsection

@include('admin.layouts._modal')

@push('styles')
  <!-- Sweet Alert -->
  <link rel="stylesheet" href=" {{ asset('vendor/sweetalert2') }}/sweetalert2.min.css">
  <!-- Select2 -->
  <link rel="stylesheet" href=" {{ asset('vendor/adminlte') }}/plugins/select2/select2.min.css">

@endpush

@push('scripts')
    <script src="{{ asset('vendor/sweetalert2') }}/sweetalert2.all.min.js"></script>
    <script src="{{ asset('vendor/adminlte') }}/plugins/select2/select2.min.js"></script>

    <script src="{{asset('vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
    <script>
      CKEDITOR.replace( 'description' );

      $('.select2').select2();
    </script>
@endpush

resources/views/admin/pages/products/images.blade.php
@extends('admin.layouts.app')

@section('title', 'Gambar Produk')

@section('card-title', 'Daftar Gambar' .$model->name)

@section('content') 

  {!! Form::open(['route' => 'product.image.store', 
                  'method' => 'POST',
                  'class' => 'form-horizontal', 
                  'enctype' => 'multipart/form-data']) !!}

      <div class="form-group row">
        {!! Form::label('name', 'Nama Gambar : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::text('name', null, ['class' => 'form-control'. ( $errors->has('name') ? ' is-invalid' : '' ), 'id' => 'name', 'placeholder' => 'Tentukan Nama Gambar Produk']) !!}
           {!! $errors->has('name') ? '<div class="invalid-feedback">'.$errors->first('name').'</div>':'' !!}
           {!! Form::hidden('product_id', $model->id) !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('image', 'Gambar : ', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          {!!Form::file('image', null, ['class' => 'form-control', 'id' => 'image']) !!}
          {!! Form::hidden('image_max_size', 5) !!}
          {!! Form::hidden('image_max_width', 2048) !!}
          {!! Form::hidden('image_max_height', 2048) !!}
          {!! $errors->has('image') ? '<div class="invalid-feedback">'.$errors->first('image').'</div>':'' !!}
        </div>
      </div>

      <div class="form-group row">
        {!! Form::label('', '', array('class' => 'col-md-3 col-form-label')) !!}
        <div class="col-md-8">
          
          {!! Form::button('Simpan', array('class' => 'btn btn-success btn-lg mr-2', 'type' => 'submit')); !!}
          {!! Form::button('Reset', array('class' => 'btn btn-warning btn-lg mr-2', 'type' => 'reset')); !!}
        </div>
      </div>

    {!! Form::close() !!}

    <table id="datatable" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>No</th>
            <th>Gambar</th>
            <th>Judul</th>
            <th>Aksi</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td> <img src="{!! asset('uploads/product/'.$model->image)  !!}" class="img img-responsive img-thumbnail" width = "60" alt=""> </td>
              <td>{!! $model->name !!}</td>
              <td></td>
            </tr>
            @php
              {{ $no =2; }}
            @endphp
            @foreach ($images as $image)
              <tr>
                <td>{!! $no !!}</td>
                <td> <img src="{!! asset('uploads/product/'.$image->image)  !!}" class="img img-responsive img-thumbnail" width = "60" alt=""> </td>
                <td>{!! $image->name !!}</td>
                <td><a href="{{ route('product.image.destroy', $image->id) }}" class="btn-delete" title="Hapus > {{ $image->name }}"><i class="fa fa-trash-o text-danger" aria-hidden="true"></i></i></a></td>
              </tr>
            @php
              {{$no++; }}
            @endphp
            @endforeach
          </tbody>
          <tfoot>
          <tr>
            <th>No</th>
            <th>Gambar</th>
            <th>Judul</th>
            <th>Aksi</th>
          </tr>
          </tfoot>
        </table>
      
@endsection

@include('admin.layouts._modal')

@push('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.css">
  <!-- Sweet Alert -->
  <link rel="stylesheet" href=" {{ asset('vendor/sweetalert2') }}/sweetalert2.min.css">
@endpush

@push('scripts')
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('vendor/sweetalert2') }}/sweetalert2.all.min.js"></script>

    <script>
      $('#datatable').DataTable({
          responsive: true,
          processing: false,
          serverSide: false,
          searching: false,
          lengthChange: false,
      });
    </script>
    
@endpush

  

resources/views/admin/pages/products/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Produk')

@section('card-title', 'Daftar Produk')

@section('content')
  
  <a href="{{ route('product.create') }}" class="btn btn-primary ml-2" title="Tambah Produk Baru"><i class="fa fa-plus"></i> Tambah</a>
  <a href="{{ route('product.export') }}" class="btn btn-success ml-2" title="Export to Excel File"><i class="fa fa-file-excel-o"></i> Export</a>
  
  <table id="datatable" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Gambar</th>
        <th>Nama Produk</th>
        <th>Kategori</th>
        <th>Tag</th>
        <th>Harga</th>
        <th>Stok</th>
        <th>Status</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
    
    </tbody>
    <tfoot>
      <tr>
        <th>No</th>
        <th>Gambar</th>
        <th>Nama Produk</th>
        <th>Kategori</th>
        <th>Tag</th>
        <th>Harga</th>
        <th>Stok</th>
        <th>Status</th>
        <th>Aksi</th>
      </tr>
    </tfoot>
  </table>
       
@endsection

@include('admin.layouts._modal')

@push('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.css">
  <!-- Sweet Alert -->
  <link rel="stylesheet" href=" {{ asset('vendor/sweetalert2') }}/sweetalert2.min.css">
@endpush

@push('scripts')
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('vendor/sweetalert2') }}/sweetalert2.all.min.js"></script>
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            searching: false,
            lengthChange: false,
            ajax: "{{ route('table.product') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id'},
                {data: 'image', name: 'image', 
                render: function( data, type, row, meta){
                  return '<img src="{{asset('uploads/product/')}}/'+data+'" class ="img img-responsive img-thumbnail" alt="'+data+'" width="60">'
                }},
                {data: 'name', name: 'name'},
                {data: 'category', name: 'category',
                render: function(data, type, row, meta){
                  return '<span class="badge badge-primary">'+data+'</span>'
                }},
                {data: 'tag', name: 'tag'},
                {data: 'price', name: 'price', render: $.fn.dataTable.render.number( '.', '.', 0, 'Rp ' )},
                {data: 'stock', name: 'stock', render: $.fn.dataTable.render.number( '.', '.', 0, '' )},
                {data: 'status', name: 'status'},
                {data: 'action', name: 'action'}
            ]
        });
    </script>
@endpush

  

resources/views/admin/pages/products/show.blade.php
<div><span>ID : </span>{{ $model->id }}</div>
<div><span>Nama : </span>{{ $model->name }}</div>
{{ $model->name }}
{{ $model->category->name }}
{{ $model->name }}
{{ $model->name }}
{{ $model->name }}