routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::prefix('admin')->group(function() {

		Route::get('/', 'Admin\DashboardController@index')->name('dashboard.index');

		Route::prefix('category')->group(function(){
			Route::name('category.')->group(function(){
				Route::post('/', 'Admin\CategoryController@store')->name('store');
				Route::get('/', 'Admin\CategoryController@index')->name('index');
				Route::get('/create', 'Admin\CategoryController@create')->name('create');
				Route::delete('/{model}', 'Admin\CategoryController@destroy')->name('destroy');
				Route::put('/{model}', 'Admin\CategoryController@update')->name('update');
				Route::get('/{model}', 'Admin\CategoryController@show')->name('show');
				Route::get('/{model}/edit', 'Admin\CategoryController@edit')->name('edit');
			});
		});
		
		Route::name('tag.')->group(function(){
			Route::post('tag', 'Admin\TagController@store')->name('store');
			Route::get('tag', 'Admin\TagController@index')->name('index');
			Route::get('tag/create', 'Admin\TagController@create')->name('create');
			Route::delete('tag/{model}', 'Admin\TagController@destroy')->name('destroy');
			Route::put('tag/{model}', 'Admin\TagController@update')->name('update');
			Route::get('tag/{model}', 'Admin\TagController@show')->name('show');
			Route::get('tag/{model}/edit', 'Admin\TagController@edit')->name('edit');
		});

		Route::name('product.')->group(function(){
			Route::post('product', 'Admin\ProductController@store')->name('store');
			Route::get('product', 'Admin\ProductController@index')->name('index');
			Route::get('product/create', 'Admin\ProductController@create')->name('create');
			Route::delete('product/{model}', 'Admin\ProductController@destroy')->name('destroy');
			Route::put('product/{model}', 'Admin\ProductController@update')->name('update');
			Route::get('product/{model}', 'Admin\ProductController@show')->name('show');
			Route::get('product/{model}/edit', 'Admin\ProductController@edit')->name('edit');
			
			Route::post('product/images', 'Admin\ProductController@imageStore')->name('image.store');
			Route::get('product/{model}/images', 'Admin\ProductController@images')->name('images');
			Route::delete('product/images/{image}', 'Admin\ProductController@imageDestroy')->name('image.destroy');
		});

		Route::get('configuration', 'Admin\ConfigurationController@edit')->name('configuration.edit');
		Route::put('configuration', 'Admin\ConfigurationController@update')->name('configuration.update');
	});

	

	Route::get('table/category', 'Admin\CategoryController@dataTable')->name('table.category');
	Route::get('table/tag', 'Admin\TagController@dataTable')->name('table.tag');
	Route::get('table/product', 'Admin\ProductController@dataTable')->name('table.product');

	Route::get('export/product', 'Admin\ProductController@export')->name('product.export');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('customer')->group(function() {
	Route::get('/login', 'Auth\CustomerLoginController@showLoginForm')->name('customer.login');
	Route::post('/login', 'Auth\CustomerLoginController@login')->name('customer.login.submit');
	Route::get('/', 'CustomerController@index')->name('customer.dashboard');
});

// Route::resource('admin/category', 'Admin\CategoryController');
Route::post('admin/users/search', 'Admin\UserController@search')->name('users.search');
Route::resource('admin/users', 'Admin\UserController');

resources/views/admin/parts/content.blade.php
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>@yield('title')</h1>
          </div>
          <div class="col-sm-6">

          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">@yield('card-title')</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
          </div>
        </div>
        <div class="card-body">
         @yield('content')
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

resources/views/admin/parts/footer.blade.php
 <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.0-alpha
    </div>
    <strong>Copyright &copy; 2014-2018 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

resources/views/admin/parts/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Abu Ibrahim Store | @yield('page-title', 'Admin ')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="csrf-token" content="{{ csrf_token() }}">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('vendor/adminlte') }}/plugins/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  @stack('styles')
  <!-- Theme style -->
  <link rel="stylesheet" href=" {{ asset('vendor/adminlte') }}/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

resources/views/admin/parts/nav.blade.php
 <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href=" ../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-comments-o"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('vendor/adminlte') }}/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('vendor/adminlte') }}/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('vendor/adminlte') }}/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-bell-o"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
          <i class="fa fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/admin/parts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="{{ asset('vendor/adminlte') }}/dist/img/AdminLTELogo.png"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
     <!-- Sidebar -->

<div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('vendor/adminlte') }}/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('dashboard.index')}}" class="nav-link  {{ request()->routeIs('dashboard.index') ? 'active':'' }}">
              <i class="nav-icon fa fa-dashboard"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>   
          <li class="nav-header">MENU</li>
          <li class="nav-item has-treeview {{ request()->routeIs(['product.*', 'category.*', 'tag.*']) ? 'menu-open':'' }}">
            <a href="#" class="nav-link {{ request()->routeIs(['product.*', 'category.*', 'tag.*']) ? 'active':'' }}">
              <i class="fa fa-cubes nav-icon"></i>
              <p>
                Produk
                <i class="fa fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('product.index')}}" class="nav-link {{ request()->routeIs('product.*') ? 'active':'' }}">
                  <i class="fa fa-dropbox nav-icon"></i>
                  <p>Produk</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('category.index')}}" class="nav-link {{ request()->routeIs('category.index') ? 'active':'' }}">
                  <i class="fa fa-th-list nav-icon"></i>
                  <p>Kategori</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('tag.index')}}" class="nav-link {{ request()->routeIs('tag.index') ? 'active':'' }}">
                  <i class="fa fa-tags nav-icon"></i>
                  <p>Tag</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="{{ route('configuration.edit')}}" class="nav-link {{ request()->routeIs('configuration.edit') ? 'active':'' }}">
              <i class="nav-icon fa fa-cogs"></i>
              <p>
                Konfigurasi
              </p>
            </a>
          </li> 
          <li class="nav-item">
            <a href="{{ route('logout') }}" class="nav-link" 
            onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
              
              <i class="nav-icon fa fa-calendar"></i>
              <p>
                {{ __('Logout') }}
              </p>
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>