routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::prefix('admin')->group(function() {

		Route::get('/', 'Admin\DashboardController@index')->name('dashboard.index');

		Route::prefix('category')->group(function(){
			Route::name('category.')->group(function(){
				Route::post('/', 'Admin\CategoryController@store')->name('store');
				Route::get('/', 'Admin\CategoryController@index')->name('index');
				Route::get('/create', 'Admin\CategoryController@create')->name('create');
				Route::delete('/{model}', 'Admin\CategoryController@destroy')->name('destroy');
				Route::put('/{model}', 'Admin\CategoryController@update')->name('update');
				Route::get('/{model}', 'Admin\CategoryController@show')->name('show');
				Route::get('/{model}/edit', 'Admin\CategoryController@edit')->name('edit');
			});
		});
		
		Route::name('tag.')->group(function(){
			Route::post('tag', 'Admin\TagController@store')->name('store');
			Route::get('tag', 'Admin\TagController@index')->name('index');
			Route::get('tag/create', 'Admin\TagController@create')->name('create');
			Route::delete('tag/{model}', 'Admin\TagController@destroy')->name('destroy');
			Route::put('tag/{model}', 'Admin\TagController@update')->name('update');
			Route::get('tag/{model}', 'Admin\TagController@show')->name('show');
			Route::get('tag/{model}/edit', 'Admin\TagController@edit')->name('edit');
		});

		Route::name('product.')->group(function(){
			Route::post('product', 'Admin\ProductController@store')->name('store');
			Route::get('product', 'Admin\ProductController@index')->name('index');
			Route::get('product/create', 'Admin\ProductController@create')->name('create');
			Route::delete('product/{model}', 'Admin\ProductController@destroy')->name('destroy');
			Route::put('product/{model}', 'Admin\ProductController@update')->name('update');
			Route::get('product/{model}', 'Admin\ProductController@show')->name('show');
			Route::get('product/{model}/edit', 'Admin\ProductController@edit')->name('edit');
			
			Route::post('product/images', 'Admin\ProductController@imageStore')->name('image.store');
			Route::get('product/{model}/images', 'Admin\ProductController@images')->name('images');
			Route::delete('product/images/{image}', 'Admin\ProductController@imageDestroy')->name('image.destroy');
		});

		Route::get('configuration', 'Admin\ConfigurationController@edit')->name('configuration.edit');
		Route::put('configuration', 'Admin\ConfigurationController@update')->name('configuration.update');
	});

	

	Route::get('table/category', 'Admin\CategoryController@dataTable')->name('table.category');
	Route::get('table/tag', 'Admin\TagController@dataTable')->name('table.tag');
	Route::get('table/product', 'Admin\ProductController@dataTable')->name('table.product');

	Route::get('export/product', 'Admin\ProductController@export')->name('product.export');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('customer')->group(function() {
	Route::get('/login', 'Auth\CustomerLoginController@showLoginForm')->name('customer.login');
	Route::post('/login', 'Auth\CustomerLoginController@login')->name('customer.login.submit');
	Route::get('/', 'CustomerController@index')->name('customer.dashboard');
});

// Route::resource('admin/category', 'Admin\CategoryController');
Route::post('admin/users/search', 'Admin\UserController@search')->name('users.search');
Route::resource('admin/users', 'Admin\UserController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
	use Sluggable;
    
   /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug', 'sort',
    ];

    /**
    * Return the sluggable configuration array for this model.
    *
    * @return array
    */
   public function sluggable()
   {
      return [
            'slug' => [
                'source' => 'name'
            ]
        ];
   }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Http\Controllers\Controller;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\DataTables;

use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.pages.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Category();
        return view('admin.pages.categories.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        return Category::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $model)
    {
        return view('admin.pages.categories.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $model)
    {
        return view('admin.pages.categories.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $model)
    {
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $model)
    {
        $model->delete();
    }


    public function dataTable()
    {
        $model = Category::query();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('admin.layouts._action', [
                    'model' => $model,
                    'url_show' => route('category.show', $model->id),
                    'url_edit' => route('category.edit', $model->id),
                    'url_destroy' => route('category.destroy', $model->id),
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make('true');
    }
}

resources/views/admin/pages/categories/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['category.update', $model->id] : 'category.store', 
    'method' => $model->exists ? 'PUT' : 'POST'
])!!}

    <div class="form-group">
        <label for="" class="control-label">Nama Kategori</label>
        {!!Form::text('name', null, ['class' => 'form-control', 'id' => 'name']) !!}
    </div>
    <div class="form-group">
        <label for="" class="control-label">Urutan</label>
        {!!Form::text('sort', null, ['class' => 'form-control', 'id' => 'sort']) !!}
    </div>
{!! Form::close() !!}

resources/views/admin/pages/categories/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Kategori')

@section('card-title', 'Daftar Kategori')

@section('content')
  
  <a href="{{ route('category.create') }}" class="btn btn-primary ml-2 modal-show" title="Tambah Kategori Baru"><i class="fa fa-plus"></i> Tambah</a>
  <a href="{{ route('category.create') }}" class="btn btn-success ml-2 modal-show" title="Export to Excel File"><i class="fa fa-file-excel-o"></i> Export</a>
  
  <table id="datatable" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama Kategori</th>
        <th>Slug Kategori</th>
        <th>Urutan</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    
    </tbody>
    <tfoot>
      <tr>
        <th>No</th>
        <th>Nama Kategori</th>
        <th>Slug Kategori</th>
        <th>Urutan</th>
        <th></th>
    </tr>
    </tfoot>
  </table>
     
@endsection

@include('admin.layouts._modal')

@push('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.css">
  <!-- Sweet Alert -->
  <link rel="stylesheet" href=" {{ asset('vendor/sweetalert2') }}/sweetalert2.min.css">
@endpush

@push('scripts')
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src=" {{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap4.min.js"></script>
     <script src="{{ asset('vendor/sweetalert2') }}/sweetalert2.all.min.js"></script>
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            searching: false,
            lengthChange: false,
            ajax: "{{ route('table.category') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'slug', name: 'slug'},
                {data: 'sort', name: 'sort'},
                {data: 'action', name: 'action'}
            ]
        });
    </script>
@endpush

  

resources/views/admin/pages/categories/show.blade.php
<table class="table table-hover">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>Slug</th>
</tr>  
<tr>
    <td>{{ $model->id }}</td>
    <td>{{ $model->name }}</td>
    <td>{{ $model->slug }}</td>
</tr>  
</table>  